name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to Railway
        uses: railwayapp/railway-action@v2
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
